config/routes.rb
Rails.application.routes.draw do

  resources :mensajes
  resources :servicios_lists
  resources :servicios
  resources :personas
  get 'home/new' => redirect("#index")

  get 'home/index'

  get 'menu/index'
  get 'menu/mensajes'
  get 'menu/servicios'
  get 'menu/nosotros'
  get 'menu/mostrar'

   root 'home#index'

   post 'consulta' => 'home#create'
      get 'mensajes/:id' => 'show#menu'

    resources :servicios do
      resources :servicios_lists
    end

end

app/models/servicio.rb
class Servicio < ActiveRecord::Base
	has_many :servicios_lists
end

app/controllers/servicios_controller.rb
class ServiciosController < ApplicationController
  before_action :set_servicio, only: [:show, :edit, :update, :destroy]

  # GET /servicios
  # GET /servicios.json
  def index
    @servicios = Servicio.all
  end

  # GET /servicios/1
  # GET /servicios/1.json
  def show
  end

  # GET /servicios/new
  def new
    @servicio = Servicio.new
  end

  # GET /servicios/1/edit
  def edit
  end

  # POST /servicios
  # POST /servicios.json
  def create
    @servicio = Servicio.new(servicio_params)

    respond_to do |format|
      if @servicio.save
        format.html { redirect_to @servicio, notice: 'Servicio was successfully created.' }
        format.json { render :show, status: :created, location: @servicio }
      else
        format.html { render :new }
        format.json { render json: @servicio.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /servicios/1
  # PATCH/PUT /servicios/1.json
  def update
    respond_to do |format|
      if @servicio.update(servicio_params)
        format.html { redirect_to @servicio, notice: 'Servicio was successfully updated.' }
        format.json { render :show, status: :ok, location: @servicio }
      else
        format.html { render :edit }
        format.json { render json: @servicio.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /servicios/1
  # DELETE /servicios/1.json
  def destroy
    @servicio.destroy
    respond_to do |format|
      format.html { redirect_to servicios_url, notice: 'Servicio was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_servicio
      @servicio = Servicio.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def servicio_params
      params.require(:servicio).permit(:nombre, :descripcion, :foto_front, :foto_back)
    end
end

app/helpers/servicios_helper.rb
module ServiciosHelper
end

app/views/servicios/_form.html.erb
<%= form_for(@servicio) do |f| %>
  <% if @servicio.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@servicio.errors.count, "error") %> prohibited this servicio from being saved:</h2>

      <ul>
      <% @servicio.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %><br>
    <%= f.text_field :nombre %>
  </div>
  <div class="field">
    <%= f.label :descripcion %><br>
    <%= f.text_field :descripcion %>
  </div>
    <div class="field">
    <%= f.label :foto_front %><br>
    <%= f.text_field :foto_front %>
  </div>
    <div class="field">
    <%= f.label :foto_back %><br>
    <%= f.text_field :foto_back %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/servicios/edit.html.erb
<h1>Editar Servicio</h1>

<%= render 'form' %>

<%= link_to 'Mostrar', @servicio %> |
<%= link_to 'Atras', servicios_path %>

app/views/servicios/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Servicios</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Descripcion</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @servicios.each do |servicio| %>
      <tr>
        <td><%= servicio.nombre %></td>
        <td><%= servicio.descripcion %></td>
        <td><%= link_to 'Mostrar', servicio %></td>
        <td><%= link_to 'Editar', edit_servicio_path(servicio) %></td>
        <td><%= link_to 'Eliminar', servicio, method: :delete, data: { confirm: 'Esta seguro de eliminar el servicio?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nuevo Servicio', new_servicio_path %>

app/views/servicios/new.html.erb
<h1>Nuevo Servicio</h1>

<%= render 'form' %>

<%= link_to 'Atras', servicios_path %>

app/views/servicios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @servicio.nombre %>
</p>

<p>
  <strong>Descripcion:</strong>
  <%= @servicio.descripcion %>
</p>

<%= link_to 'Editar', edit_servicio_path(@servicio) %> |
<%= link_to 'Atras', servicios_path %>