config/routes.rb
Rails.application.routes.draw do

  resources :mensajes
  resources :servicios_lists
  resources :servicios
  resources :personas
  get 'home/new' => redirect("#index")

  get 'home/index'

  get 'menu/index'
  get 'menu/mensajes'
  get 'menu/servicios'
  get 'menu/nosotros'
  get 'menu/mostrar'

   root 'home#index'

   post 'consulta' => 'home#create'
      get 'mensajes/:id' => 'show#menu'

    resources :servicios do
      resources :servicios_lists
    end

end

app/models/servicios_list.rb
class ServiciosList < ActiveRecord::Base
  belongs_to :servicios
end

app/controllers/servicios_lists_controller.rb
class ServiciosListsController < ApplicationController
  before_action :set_servicios_list, only: [:show, :edit, :update, :destroy]

  # GET /servicios_lists
  # GET /servicios_lists.json
  def index
    @servicios = Servicio.all
    @servicios_lists = ServiciosList.all
  end

  # GET /servicios_lists/1
  # GET /servicios_lists/1.json
  def show
  end

  # GET /servicios_lists/new
  def new
    @servicios_list = ServiciosList.new
  end

  # GET /servicios_lists/1/edit
  def edit
  end

  # POST /servicios_lists
  # POST /servicios_lists.json
  def create
    @servicios_list = ServiciosList.new(servicios_list_params)

    respond_to do |format|
      if @servicios_list.save
        format.html { redirect_to @servicios_list, notice: 'Servicios list was successfully created.' }
        format.json { render :show, status: :created, location: @servicios_list }
      else
        format.html { render :new }
        format.json { render json: @servicios_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /servicios_lists/1
  # PATCH/PUT /servicios_lists/1.json
  def update
    respond_to do |format|
      if @servicios_list.update(servicios_list_params)
        format.html { redirect_to @servicios_list, notice: 'Servicios list was successfully updated.' }
        format.json { render :show, status: :ok, location: @servicios_list }
      else
        format.html { render :edit }
        format.json { render json: @servicios_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /servicios_lists/1
  # DELETE /servicios_lists/1.json
  def destroy
    @servicios_list.destroy
    respond_to do |format|
      format.html { redirect_to servicios_lists_url, notice: 'Servicios list was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_servicios_list
      @servicios_list = ServiciosList.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def servicios_list_params
      params.require(:servicios_list).permit(:servicio, :descripcion, :servicio_id)
    end
end

app/helpers/servicios_lists_helper.rb
module ServiciosListsHelper
end

app/views/servicios_lists/_form.html.erb
<%= form_for(@servicios_list) do |f| %>
  <% if @servicios_list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@servicios_list.errors.count, "error") %> prohibited this servicios_list from being saved:</h2>

      <ul>
      <% @servicios_list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :servicio %><br>
    <%= f.text_field :servicio %>
  </div>
  <div class="field">
    <%= f.label :descripcion %><br>
    <%= f.text_field :descripcion %>
  </div>
  <div class="field">
    <%= f.label :servicio_id %><br>
    <%= f.collection_select :servicio_id, Servicio.all, :id, :nombre %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/servicios_lists/edit.html.erb
<h1>Editar Servicios List</h1>

<%= render 'form' %>

<%= link_to 'Mostrar', @servicios_list %> |
<%= link_to 'Atras', servicios_lists_path %>

app/views/servicios_lists/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Servicios Lists</h1>

<table>
  <thead>
    <tr>
      <th>Descripcion</th>
      <th>Servicios</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @servicios_lists.each do |servicios_list| %>
      <tr>
        <td><%= servicios_list.descripcion %></td>
        <td><%= servicios_list.servicio_id %></td>
        <td><%= link_to 'Mostrar', servicios_list %></td>
        <td><%= link_to 'Editar', edit_servicios_list_path(servicios_list) %></td>
        <td><%= link_to 'Eliminar', servicios_list, method: :delete, data: { confirm: 'Esta seguro de eliminar la lista?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nuevo Servicios list', new_servicios_list_path %>

app/views/servicios_lists/new.html.erb
<h1>Nuevo Servicios List</h1>

<%= render 'form' %>

<%= link_to 'Atras', servicios_lists_path %>

app/views/servicios_lists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Servicio:</strong>
  <%= @servicios_list.servicio %>
</p>

<p>
  <strong>Descripcion:</strong>
  <%= @servicios_list.descripcion %>
</p>

<p>
  <strong>Servicios:</strong>
  <%= @servicios_list.servicio_id %>
</p>

<%= link_to 'Editar', edit_servicios_list_path(@servicios_list) %> |
<%= link_to 'Atras', servicios_lists_path %>