config/routes.rb
Rails.application.routes.draw do

  resources :mensajes
  resources :servicios_lists
  resources :servicios
  resources :personas
  get 'home/new' => redirect("#index")

  get 'home/index'

  get 'menu/index'
  get 'menu/mensajes'
  get 'menu/servicios'
  get 'menu/nosotros'
  get 'menu/mostrar'

   root 'home#index'

   post 'consulta' => 'home#create'
      get 'mensajes/:id' => 'show#menu'

    resources :servicios do
      resources :servicios_lists
    end

end

app/models/mensaje.rb
class Mensaje < ActiveRecord::Base
end

app/controllers/mensajes_controller.rb
class MensajesController < ApplicationController
  before_action :set_mensaje, only: [:show, :edit, :update, :destroy]

  # GET /mensajes
  # GET /mensajes.json
  def index
    @mensajes = Mensaje.all
  end

  # GET /mensajes/1
  # GET /mensajes/1.json
  def show
  end

  # GET /mensajes/new
  def new
    @mensaje = Mensaje.new
  end

  # GET /mensajes/1/edit
  def edit
  end

  # POST /mensajes
  # POST /mensajes.json
  def create
    @mensaje = Mensaje.new(mensaje_params)

    respond_to do |format|
      if @mensaje.save
        format.html { redirect_to @mensaje, notice: 'Mensaje was successfully created.' }
        format.json { render :show, status: :created, location: @mensaje }
      else
        format.html { render :new }
        format.json { render json: @mensaje.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mensajes/1
  # PATCH/PUT /mensajes/1.json
  def update
    respond_to do |format|
      if @mensaje.update(mensaje_params)
        format.html { redirect_to @mensaje, notice: 'Mensaje was successfully updated.' }
        format.json { render :show, status: :ok, location: @mensaje }
        format.js
      else
        format.html { render :edit }
        format.json { render json: @mensaje.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mensajes/1
  # DELETE /mensajes/1.json
  def destroy
    @mensaje.destroy
    respond_to do |format|
      format.html { redirect_to mensajes_url, notice: 'Mensaje was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mensaje
      @mensaje = Mensaje.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def mensaje_params
      params.require(:mensaje).permit(:nombre, :mail, :telefono, :consulta, :leido)
    end
end

app/helpers/mensajes_helper.rb
module MensajesHelper
end

app/views/mensajes/_form.html.erb
<%= form_for(@mensaje) do |f| %>
  <% if @mensaje.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@mensaje.errors.count, "error") %> prohibited this mensaje from being saved:</h2>

      <ul>
      <% @mensaje.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %><br>
    <%= f.text_field :nombre %>
  </div>
  <div class="field">
    <%= f.label :mail %><br>
    <%= f.text_field :mail %>
  </div>
  <div class="field">
    <%= f.label :telefono %><br>
    <%= f.text_field :telefono %>
  </div>
  <div class="field">
    <%= f.label :consulta %><br>
    <%= f.text_field :consulta %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/mensajes/edit.html.erb
<h1>Editar Mensaje</h1>

<%= render 'form' %>

<%= link_to 'Mostrar', @mensaje %> |
<%= link_to 'Atras', mensajes_path %>

app/views/mensajes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Mensajes</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Mail</th>
      <th>Telefono</th>
      <th>Consulta</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @mensajes.each do |mensaje| %>
      <tr>
        <td><%= mensaje.nombre %></td>
        <td><%= mensaje.mail %></td>
        <td><%= mensaje.telefono %></td>
        <td><%= mensaje.consulta %></td>
        <td><%= link_to 'Mostrar', mensaje %></td>
        <td><%= link_to 'Editar', edit_mensaje_path(mensaje) %></td>
        <td><%= link_to 'Eliminar', mensaje, method: :delete, data: { confirm: 'Esta seguro de eliminar el mensaje?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nuevo Mensaje', new_mensaje_path %>

app/views/mensajes/new.html.erb
<h1>Nuevo Mensaje</h1>

<%= render 'form' %>

<%= link_to 'Atras', mensajes_path %>

app/views/mensajes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @mensaje.nombre %>
</p>

<p>
  <strong>Mail:</strong>
  <%= @mensaje.mail %>
</p>

<p>
  <strong>Telefono:</strong>
  <%= @mensaje.telefono %>
</p>

<p>
  <strong>Consulta:</strong>
  <%= @mensaje.consulta %>
</p>

<%= link_to 'Editar', edit_mensaje_path(@mensaje) %> |
<%= link_to 'Atras', mensajes_path %>